baseurl:
url: https://jcelerier.name
title: Personal website of Jean-Michaël Celerier
email: jeanmichael.celerier@gmail.com
subtitle: post-*
author: Jean-Michaël Celerier
simple_search: https://google.com/search
description: Personal website of Jean-Michaël Celerier
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Europe/Paris
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
include: ["robots.txt", "favicon.ico"]
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: code
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/perso/jcelerier.github.io
